---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins
rules:
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch']
  - apiGroups: ['']
    resources: ['pods/exec']
    verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch']
  - apiGroups: ['']
    resources: ['pods/log']
    verbs: ['get', 'delete', 'list', 'watch']
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch']
  - apiGroups: ['']
    resources: ['configmaps']
    verbs: ['create', 'delete', 'get', 'list', 'patch', 'update']
  - apiGroups: ['apps']
    resources: ['deployments', 'pods', 'daemonsets']
    verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch']
  - apiGroups: ['']
    resources: ['services']
    verbs: ['create', 'delete', 'get', 'list', 'patch', 'update']
  - apiGroups: ['']
    resources: ['ingresses']
    verbs: ['create', 'get', 'list', 'patch', 'update']
  - apiGroups: ['*']
    resources: ['namespaces']
    verbs: ['get', 'list', 'watch', 'create']
  - apiGroups: ['']
    resources: ['persistentvolumes']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources: ['persistentvolumeclaims']
    verbs: ['create', 'get', 'list', 'patch', 'update']
  - apiGroups: ['']
    resources: ['serviceaccounts']
    verbs: ['create', 'get', 'list', 'patch', 'update']

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins
subjects:
  - kind: User
    name: jenkins
  - kind: ServiceAccount
    name: default
    namespace: jenkins
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins
roleRef:
  kind: ClusterRole
  name: jenkins
  apiGroup: rbac.authorization.k8s.io
